/**
 * CADRE — Recurring block generator: "PT every weekday 0600–0700 for 6 weeks".
 * Generates one session per matching day between two dates, batched.
 */
import React, { useMemo, useState } from 'react';
import { collection, doc, serverTimestamp, writeBatch } from 'firebase/firestore';
import { db } from '../../lib/firebase';
import { shortId, useCollection, type WithId } from '../../lib/firestore';
import { useAuth } from '../../auth/AuthContext';
import { addDays, combineDateTime, hoursBetween, toDateInputValue, tsFromDate } from '../../lib/time';
import type { AcademyDoc, CourseDoc, RoleSlot } from '../../types';
import { Button, Field, Input, Select } from '../../components/ui';
import { Modal } from '../../components/Modal';
import { logAudit } from '../sessions/audit';

const WEEKDAYS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];

export function RecurringGeneratorModal({ academy, onClose }: { academy: WithId<AcademyDoc>; onClose: () => void }) {
  const { firebaseUser } = useAuth();
  const { data: courses } = useCollection<CourseDoc>('courseCatalog');

  const [courseId, setCourseId] = useState('');
  const [days, setDays] = useState<Set<number>>(new Set([1, 2, 3, 4, 5])); // weekdays
  const [from, setFrom] = useState(toDateInputValue(academy.startDate.toDate()));
  const [until, setUntil] = useState(toDateInputValue(academy.endDate.toDate()));
  const [startTime, setStartTime] = useState('06:00');
  const [endTime, setEndTime] = useState('07:00');
  const [room, setRoom] = useState(academy.defaultRoom ?? '');
  const [busy, setBusy] = useState(false);

  const course = courses.find((c) => c.id === courseId);

  const matchingDates = useMemo(() => {
    const out: Date[] = [];
    if (!from || !until) return out;
    let d = new Date(`${from}T00:00:00`);
    const end = new Date(`${until}T00:00:00`);
    while (d <= end) {
      if (days.has(d.getDay())) out.push(new Date(d));
      d = addDays(d, 1);
    }
    return out;
  }, [from, until, days]);

  function toggleDay(i: number) {
    setDays((prev) => {
      const next = new Set(prev);
      if (next.has(i)) next.delete(i);
      else next.add(i);
      return next;
    });
  }

  async function submit(e: React.FormEvent) {
    e.preventDefault();
    if (!course || !firebaseUser) return;
    setBusy(true);

    const slots = (): RoleSlot[] => [
      {
        slotId: shortId(),
        role: 'lead',
        count: 1,
        requiredQualificationKey: course.leadRequiredQualificationKey,
        filledBy: [],
      },
      ...course.defaultRoleSlots
        .filter((s) => s.role !== 'lead')
        .map((s) => ({ slotId: shortId(), filledBy: [], ...s })),
    ];

    let batch = writeBatch(db);
    let count = 0;
    for (const date of matchingDates) {
      const ds = toDateInputValue(date);
      const start = combineDateTime(ds, startTime);
      const end = combineDateTime(ds, endTime);
      batch.set(doc(collection(db, 'sessions')), {
        academyId: academy.id,
        courseId: course.id,
        courseName: course.name,
        highLiability: course.highLiability,
        title: '',
        start: tsFromDate(start),
        end: tsFromDate(end),
        location: academy.location,
        room,
        hours: hoursBetween(start, end),
        status: academy.status === 'draft' ? 'draft' : 'scheduled',
        roleSlots: slots(),
        notes: 'Generated by recurring block tool',
        createdBy: firebaseUser.uid,
        updatedAt: serverTimestamp(),
      });
      if (++count % 400 === 0) {
        await batch.commit();
        batch = writeBatch(db);
      }
    }
    await batch.commit();
    await logAudit(
      firebaseUser.uid,
      'session.bulk_create',
      'academy',
      academy.id,
      `Generated ${matchingDates.length} recurring "${course.name}" sessions`
    );
    setBusy(false);
    onClose();
  }

  return (
    <Modal open onClose={onClose} title="Recurring block generator">
      <form onSubmit={submit} className="space-y-4">
        <Field label="Course">
          <Select value={courseId} onChange={(e) => setCourseId(e.target.value)} required>
            <option value="">Select a course…</option>
            {courses.map((c) => (
              <option key={c.id} value={c.id}>
                {c.name}
              </option>
            ))}
          </Select>
        </Field>
        <fieldset>
          <legend className="mb-1 text-sm font-medium text-watch-800">Repeat on</legend>
          <div className="flex gap-1.5">
            {WEEKDAYS.map((label, i) => (
              <button
                key={label}
                type="button"
                aria-pressed={days.has(i)}
                onClick={() => toggleDay(i)}
                className={`rounded-md px-2.5 py-1.5 text-xs font-medium ring-1 ring-inset ${
                  days.has(i) ? 'bg-watch-800 text-bifrost-300 ring-watch-800' : 'bg-white text-slate-600 ring-watch-200'
                }`}
              >
                {label}
              </button>
            ))}
          </div>
        </fieldset>
        <div className="grid grid-cols-2 gap-4">
          <Field label="From">
            <Input type="date" value={from} onChange={(e) => setFrom(e.target.value)} required />
          </Field>
          <Field label="Until">
            <Input type="date" value={until} onChange={(e) => setUntil(e.target.value)} required />
          </Field>
        </div>
        <div className="grid grid-cols-3 gap-4">
          <Field label="Start time">
            <Input type="time" value={startTime} onChange={(e) => setStartTime(e.target.value)} required />
          </Field>
          <Field label="End time">
            <Input type="time" value={endTime} onChange={(e) => setEndTime(e.target.value)} required />
          </Field>
          <Field label="Room">
            <Input value={room} onChange={(e) => setRoom(e.target.value)} required />
          </Field>
        </div>
        <p className="text-sm text-slate-500">
          Will create <strong className="text-watch-900">{matchingDates.length}</strong> sessions.
        </p>
        <div className="flex justify-end gap-2">
          <Button type="button" variant="ghost" onClick={onClose}>
            Cancel
          </Button>
          <Button type="submit" variant="primary" disabled={busy || !courseId || matchingDates.length === 0}>
            Generate {matchingDates.length} sessions
          </Button>
        </div>
      </form>
    </Modal>
  );
}
