/**
 * Printable / PDF-friendly academy schedule with the HEIMDALL-branded header.
 * Rendered outside the app shell; the print stylesheet strips chrome.
 */
import React, { useMemo } from 'react';
import { useParams } from 'react-router-dom';
import { orderBy, where } from 'firebase/firestore';
import { useCollection, useDoc } from '../../lib/firestore';
import { useGlobalSettings } from '../../app/providers';
import { fmtTime } from '../../lib/time';
import type { AcademyDoc, SessionDoc } from '../../types';
import { DISCIPLINE_LABELS, SLOT_ROLE_LABELS } from '../../types';
import { WordmarkHorizontal } from '../../brand/Logo';
import { Button } from '../../components/ui';

export function PrintableSchedulePage() {
  const { academyId } = useParams<{ academyId: string }>();
  const settings = useGlobalSettings();
  const { data: academy } = useDoc<AcademyDoc>(academyId ? `academies/${academyId}` : null);
  const { data: sessions } = useCollection<SessionDoc>(
    academyId ? 'sessions' : null,
    [where('academyId', '==', academyId ?? ''), orderBy('start')],
    [academyId]
  );

  const byDay = useMemo(() => {
    const map = new Map<string, typeof sessions>();
    for (const s of sessions) {
      if (s.status === 'cancelled') continue;
      const key = s.start.toDate().toLocaleDateString(undefined, {
        weekday: 'long',
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      });
      map.set(key, [...(map.get(key) ?? []), s]);
    }
    return map;
  }, [sessions]);

  if (!academy) return null;
  const totalHours = sessions.filter((s) => s.status !== 'cancelled').reduce((n, s) => n + s.hours, 0);

  return (
    <div className="mx-auto max-w-4xl bg-white px-8 py-8 text-black">
      {/* Branded print header */}
      <header className="mb-6 flex items-start justify-between border-b-2 border-black pb-4">
        <div>
          <WordmarkHorizontal size={30} className="text-black" />
          <div className="mt-1 text-xs uppercase tracking-[0.18em] text-slate-600">
            {settings?.orgName ?? 'Training Academy'} · CADRE Master Schedule
          </div>
        </div>
        <div className="text-right text-sm">
          <div className="text-lg font-bold">{academy.name}</div>
          <div>{academy.fdleProgram}</div>
          <div>
            {academy.startDate.toDate().toLocaleDateString()} – {academy.endDate.toDate().toLocaleDateString()} ·{' '}
            {totalHours} / {academy.targetTotalHours} hrs
          </div>
        </div>
      </header>

      <div className="no-print mb-4">
        <Button variant="primary" onClick={() => window.print()}>
          Print / Save as PDF
        </Button>
      </div>

      {[...byDay.entries()].map(([day, daySessions]) => (
        <section key={day} className="mb-4 break-inside-avoid">
          <h2 className="border-b border-slate-300 pb-1 text-sm font-bold uppercase tracking-wide">{day}</h2>
          <table className="w-full text-sm">
            <tbody>
              {daySessions.map((s) => (
                <tr key={s.id} className="border-b border-slate-100 align-top">
                  <td className="w-28 py-1.5 font-mono text-xs">
                    {fmtTime(s.start)}–{fmtTime(s.end)}
                  </td>
                  <td className="py-1.5">
                    <span className="font-medium">{s.title || s.courseName}</span>
                    {s.highLiability && <span className="ml-2 text-xs font-bold">▲ HIGH-LIABILITY</span>}
                    <div className="text-xs text-slate-600">
                      {s.roleSlots
                        .map((sl) => `${sl.count}× ${SLOT_ROLE_LABELS[sl.role]}`)
                        .join(' · ')}
                    </div>
                  </td>
                  <td className="w-32 py-1.5 text-xs">{s.room}</td>
                  <td className="w-14 py-1.5 text-right text-xs">{s.hours} h</td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>
      ))}

      <footer className="mt-8 border-t border-slate-300 pt-3 text-center text-xs text-slate-500">
        Generated by HEIMDALL · Sounded by Gjallarhorn
      </footer>
    </div>
  );
}
